### ISSUE TITLE
录制结束文件回调有吗

### ISSUE THREAD

**Issue by NuonuoLabs** [Hellobird/VideoRecord#1]
请问你这录制结束时的视频在哪里能拿到？

**Comment by Hellobird** [comment]
录制的适配是根据你传入的路径来保存，如果没传的话是保存到 context.getExternalCacheDir().getAbsolutePath() + File.separator + "temp.mp4" 的

**Comment by Hellobird** [comment]
录制的适配是根据你传入的路径来保存，如果没传的话是保存到 context.getExternalCacheDir().getAbsolutePath() + File.separator + "temp.mp4" 的
